### ISSUE TITLE
Script execution

### ISSUE THREAD

**Issue by ShivamSarodia** [tevko/practice#13]
When an issue contains HTML code, the code is rendered by the browser, leaving open the potential for unsafe script execution.

**Comment by tevko** [comment]
Wow good catch, thanks

On Wed, Jul 9, 2014 at 5:29 PM, ShivamSarodia notifications@github.com
wrote:

> When an issue contains HTML code, the code is rendered by the browser,
> leaving open the potential for unsafe script execution.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tevko/practice/issues/13.

## 

Tim Evko

//timevko.com

**Comment by tevko** [comment]
text = $('.markdown').contents().filter(function() {
    return this.nodeType == 3;
}).text(),
.text() returns the non-escaped version of the HTML, it needs to be .html() to return the escaped version.

**Comment by tevko** [comment]
fixed by adding Markdown.Sanitizer.js
