### ISSUE TITLE
Dribbble API credentials issue

### ISSUE THREAD

**Issue by omgmog** [tevko/practice#30]
Did you break something, or are you reaching the rate limit?

Perhaps moving to a solution where you periodically cache the Dribbble search call somewhere might help?

Noticed this because somebody shared this on DN, and people are complaining about the API error! https://news.layervault.com/stories/45683-the-ultimate-front-end-practice-app-for-developers

**Comment by tevko** [comment]
Definitely a rate limit. We were caching initially ... let me check

**Comment by tevko** [comment]
It's actually a Bad credentials error?

**Comment by omgmog** [comment]
Is the App still registered on your Dribbble account?

**Comment by omgmog** [comment]
Also, make sure you're using the "Client Access Token" in main.js

**Comment by tevko** [comment]
just reset to this - https://api.dribbble.com/v1/user?access_token=6ed972085fecb7078ef53a3056562c05de38514ebd7d095b6a84f6dba7743031

still broken

**Comment by omgmog** [comment]
I've tested with mine and I get a 200, so it's fine there:

```
$.ajax('https://api.dribbble.com/v1/shots?page=4&access_token=6288d1baba6d36c25f2b62037e644f450d6e8d2b8c68d064bae2adeed090d6d3');
```

**Comment by tevko** [comment]
works now

**Comment by tevko** [comment]
fixing

**Comment by tevko** [comment]
Okay, just fixed. Let's see if this surfaces again. Thanks for the heads up
